[build]
builder = "nixpacks"

[deploy]
startCommand = "node server.js"
restartPolicyType = "ON_FAILURE"  
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 15
replicas = 1

[variables]
NODE_ENV = "production"